name: E2E (Cypress)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [20]
        browser: [chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser ${{ matrix.browser }}
          config-file: cypress.config.js
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}

      # Upload videos & screenshots (always handy for debugging)
      - name: Upload Cypress videos
        if: always() # run step even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload Cypress screenshots
        if: always() # run step even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          if-no-files-found: ignore